# Generated by Django 6.0.6 on 2026-06-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Rozee', 'Rozee'), ('Indeed', 'Indeed'), ('Referral', 'Referral'), ('Company Website', 'Company Website')], max_length=50)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('applied_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
